-- =====================================================================
--  SCRIPT 1/2 : SCHEMA (structure des tables)
--  A executer EN PREMIER dans DBeaver  (Alt+X = Execute script)
-- =====================================================================

DROP VIEW  IF EXISTS v_position CASCADE;
DROP TABLE IF EXISTS csv_upload_log       CASCADE;
DROP TABLE IF EXISTS audit_log            CASCADE;
DROP TABLE IF EXISTS market_rates         CASCADE;
DROP TABLE IF EXISTS external_pnl_snapshot CASCADE;
DROP TABLE IF EXISTS tbill_position       CASCADE;
DROP TABLE IF EXISTS pnl_daily            CASCADE;
DROP TABLE IF EXISTS portfolio_limit      CASCADE;
DROP TABLE IF EXISTS trader_limit         CASCADE;
DROP TABLE IF EXISTS risk_metrics         CASCADE;
DROP TABLE IF EXISTS pricing_config       CASCADE;
DROP TABLE IF EXISTS coupon_received      CASCADE;
DROP TABLE IF EXISTS market_data          CASCADE;
DROP TABLE IF EXISTS trade                CASCADE;
DROP TABLE IF EXISTS app_user             CASCADE;
DROP TABLE IF EXISTS instrument           CASCADE;

CREATE TABLE instrument (
    isin                 VARCHAR(12)   PRIMARY KEY,
    description          VARCHAR(200)  NOT NULL,
    issuer               VARCHAR(20)   NOT NULL,
    currency             VARCHAR(3)    NOT NULL,
    sub_asset            VARCHAR(20)   NOT NULL,
    coupon_rate          NUMERIC(8,4)  NOT NULL,
    coupon_frequency     SMALLINT      NOT NULL,
    maturity_date        DATE          NOT NULL,
    issue_date           DATE,
    nominal_outstanding  BIGINT,
    is_active            BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_user (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    email         VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(60)  NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    full_name     VARCHAR(100),
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    last_login_at TIMESTAMP,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE trade (
    id               BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_identifier VARCHAR(255),
    trade_date       DATE          NOT NULL,
    value_date       DATE,
    isin             VARCHAR(12),
    sub_asset        VARCHAR(20)   NOT NULL,
    way              VARCHAR(4)    NOT NULL,
    nominal          NUMERIC(20,2) NOT NULL,
    counterparty     VARCHAR(100),
    commission_type  VARCHAR(50),
    trade_category   VARCHAR(30),
    clean_price      NUMERIC(15,10),
    accrued          NUMERIC(15,10),
    dirty_price      NUMERIC(15,10),
    wap_dirty        NUMERIC(15,10),
    wap_clean        NUMERIC(15,10),
    realized_pnl     NUMERIC(20,2),
    mtm_pnl          NUMERIC(20,2),
    nb_contracts     INTEGER,
    contract_size    NUMERIC,
    last_price       NUMERIC,
    hed_bond_isin    VARCHAR(255),
    g_spread         NUMERIC,
    is_closed        BOOLEAN       NOT NULL DEFAULT FALSE,
    upload_log_id    BIGINT,
    created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_trade_instrument FOREIGN KEY (isin) REFERENCES instrument (isin)
);
CREATE INDEX idx_trade_isin       ON trade (isin);
CREATE INDEX idx_trade_trade_date ON trade (trade_date);

CREATE TABLE market_data (
    id                BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isin              VARCHAR(12)   NOT NULL,
    data_date         DATE          NOT NULL,
    px_last           NUMERIC(15,10),
    px_mid            NUMERIC(15,10),
    accrued_bloomberg NUMERIC(15,10),
    px_bid_awb        NUMERIC(15,10),
    px_ask_awb        NUMERIC(15,10),
    g_spread_bid      NUMERIC(10,4),
    g_spread_ask      NUMERIC(10,4),
    i_spread_bid      NUMERIC(10,4),
    i_spread_ask      NUMERIC(10,4),
    created_at        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_market_data_instrument FOREIGN KEY (isin) REFERENCES instrument (isin)
);
CREATE INDEX idx_market_data_isin ON market_data (isin);
CREATE INDEX idx_market_data_date ON market_data (data_date);

CREATE TABLE coupon_received (
    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isin         VARCHAR(12)   NOT NULL,
    payment_date DATE          NOT NULL,
    amount       NUMERIC(18,4) NOT NULL,
    currency     VARCHAR(3)    NOT NULL,
    created_at   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_coupon_instrument FOREIGN KEY (isin) REFERENCES instrument (isin)
);
CREATE INDEX idx_coupon_isin ON coupon_received (isin);

CREATE TABLE pricing_config (
    id                    BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isin                  VARCHAR(12)   NOT NULL,
    config_date           DATE          NOT NULL,
    g_spread_bid          NUMERIC(15,4),
    g_spread_ask          NUMERIC(15,4),
    historical_avg_spread NUMERIC(10,4),
    shock_bps             INTEGER       NOT NULL DEFAULT 10,
    target_spread         NUMERIC(10,4),
    decision              VARCHAR(10),
    created_at            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP,
    CONSTRAINT uq_pricing_isin_date UNIQUE (isin, config_date),
    CONSTRAINT fk_pricing_instrument FOREIGN KEY (isin) REFERENCES instrument (isin)
);

CREATE TABLE risk_metrics (
    id                BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isin              VARCHAR(12)   NOT NULL,
    metrics_date      DATE          NOT NULL,
    maturity_years    NUMERIC(8,4),
    modified_duration NUMERIC(8,6),
    dv01_per_million  NUMERIC(12,4),
    ytm_mid           NUMERIC(10,6),
    hedge_future      VARCHAR(20),
    ctd_isin          VARCHAR(20),
    duration_ctd      NUMERIC(8,6),
    contract_size     INTEGER       DEFAULT 100000,
    conv_factor       NUMERIC(8,6),
    convexity         NUMERIC(10,4),
    created_at        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_risk_isin_date UNIQUE (isin, metrics_date),
    CONSTRAINT fk_risk_instrument FOREIGN KEY (isin) REFERENCES instrument (isin)
);

CREATE TABLE trader_limit (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT        NOT NULL,
    instrument_type VARCHAR(20)   NOT NULL,
    limit_amount    NUMERIC(18,2) NOT NULL,
    currency        VARCHAR(3)    NOT NULL,
    used_amount     NUMERIC(18,2) DEFAULT 0,
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP,
    CONSTRAINT uq_trader_limit UNIQUE (user_id, instrument_type),
    CONSTRAINT fk_trader_limit_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);
CREATE INDEX idx_trader_limit_user ON trader_limit (user_id);

CREATE TABLE portfolio_limit (
    id                 BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_name     VARCHAR(50)   NOT NULL,
    limit_meur         NUMERIC(10,2) NOT NULL,
    max_duration_years NUMERIC(4,2)  DEFAULT 7.00,
    limit_type         VARCHAR(20)   NOT NULL DEFAULT 'EXPOSURE',
    currency           VARCHAR(3)    DEFAULT 'EUR',
    category           VARCHAR(30),
    color_token        VARCHAR(40),
    effective_date     DATE          NOT NULL,
    is_active          BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pnl_daily (
    id                    BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_date         DATE          NOT NULL UNIQUE,
    pnl_total_gestion_mad NUMERIC(20,2),
    pnl_jour_mad          NUMERIC(20,2),
    position_eur_usd      NUMERIC(20,2),
    position_usd          NUMERIC(20,2),
    taux_eur              NUMERIC(10,6),
    taux_usd              NUMERIC(10,6),
    fin_eur_mad           NUMERIC(20,2),
    fin_usd_mad           NUMERIC(20,2),
    fin_total_mad         NUMERIC(20,2),
    fin_cumul_mad         NUMERIC(20,2),
    pnl_eco_mad           NUMERIC(20,2),
    pl_bond_eur           NUMERIC(20,2),
    pl_bond_usd           NUMERIC(20,2),
    pl_fut_eur            NUMERIC(20,2),
    pl_fut_usd            NUMERIC(20,2),
    created_at            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tbill_position (
    id                BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isin              VARCHAR(12)   NOT NULL,
    emetteur          VARCHAR(100)  NOT NULL,
    devise            VARCHAR(3)    NOT NULL,
    snapshot_date     DATE          NOT NULL,
    nominal           NUMERIC(20,2) NOT NULL,
    yield_net         NUMERIC(8,4),
    yield_brut        NUMERIC(8,4),
    duration          NUMERIC(8,4),
    pl_yield_usd      NUMERIC(18,2),
    pl_fx_usd         NUMERIC(18,2),
    pl_eco_usd        NUMERIC(18,2),
    funding_usd       NUMERIC(18,2),
    fx_moyen          NUMERIC(10,4),
    fx_current        NUMERIC(10,4),
    fx_breakeven_avec NUMERIC(10,4),
    fx_breakeven_sans NUMERIC(10,4),
    fx_stop_loss      NUMERIC(10,4),
    maturity_date     DATE          NOT NULL,
    date_initiation   DATE,
    limit_nominal     NUMERIC(20,2),
    created_at        TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE external_pnl_snapshot (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isin            VARCHAR(20)   NOT NULL,
    description     VARCHAR(255),
    asset_category  VARCHAR(20)   NOT NULL,
    snapshot_date   DATE          NOT NULL,
    nominal_usd     NUMERIC(20,2),
    coupon_rate     NUMERIC(8,6),
    counterparty    VARCHAR(100),
    maturity_date   DATE,
    pl_realized_usd NUMERIC(18,4),
    pl_latent_usd   NUMERIC(18,4),
    pl_eco_usd      NUMERIC(18,4),
    pl_eco_mad      NUMERIC(18,2),
    funding_usd     NUMERIC(18,4),
    duration        NUMERIC(8,4),
    wap_fx_entry    NUMERIC(14,6),
    source          VARCHAR(50),
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE market_rates (
    id         BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rate_date  DATE          NOT NULL UNIQUE,
    eur_mad    NUMERIC(12,6) NOT NULL,
    usd_mad    NUMERIC(12,6) NOT NULL,
    eur_usd    NUMERIC(10,6) NOT NULL,
    estr_rate  NUMERIC(10,6) NOT NULL,
    sofr_rate  NUMERIC(10,6) NOT NULL,
    usd_egp    NUMERIC(10,4),
    cbe_rate   NUMERIC(10,4),
    shock_bps  INTEGER       NOT NULL DEFAULT 10,
    created_at TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE audit_log (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50) NOT NULL,
    table_name VARCHAR(50) NOT NULL,
    action     VARCHAR(10) NOT NULL,
    record_id  BIGINT,
    details    JSONB,
    ip_address VARCHAR(45),
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_audit_created ON audit_log (created_at DESC);
CREATE INDEX idx_audit_user    ON audit_log (username);
CREATE INDEX idx_audit_table   ON audit_log (table_name, action);

CREATE TABLE csv_upload_log (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename       VARCHAR(255) NOT NULL,
    uploaded_by    VARCHAR(100) NOT NULL,
    uploaded_at    TIMESTAMP    NOT NULL,
    total_lines    INTEGER      DEFAULT 0,
    imported_count INTEGER      DEFAULT 0,
    error_count    INTEGER      DEFAULT 0,
    error_details  JSONB,
    status         VARCHAR(20)  NOT NULL DEFAULT 'PROCESSING',
    duration_ms    INTEGER
);

DROP VIEW IF EXISTS v_position;
CREATE VIEW v_position AS
SELECT
    i.isin,
    i.description,
    i.currency,
    i.sub_asset,
    i.coupon_rate,
    i.maturity_date,
    COALESCE(
        SUM(CASE WHEN t.way = 'BUY'  THEN  t.nominal
                 WHEN t.way = 'SELL' THEN -t.nominal
                 ELSE 0 END), 0) AS net_nominal,
    (SELECT t2.wap_dirty FROM trade t2
      WHERE t2.isin = i.isin AND t2.way = 'BUY' AND t2.is_closed = false
      ORDER BY t2.trade_date DESC, t2.id DESC LIMIT 1) AS wap_dirty,
    (SELECT t2.wap_clean FROM trade t2
      WHERE t2.isin = i.isin AND t2.way = 'BUY' AND t2.is_closed = false
      ORDER BY t2.trade_date DESC, t2.id DESC LIMIT 1) AS wap_clean,
    COALESCE(SUM(COALESCE(t.realized_pnl, 0)), 0) AS total_realized_pnl,
    COUNT(CASE WHEN t.way = 'BUY' AND t.is_closed = false THEN 1 END) AS nb_open_buy_trades,
    COUNT(*) AS total_trades
FROM instrument i
INNER JOIN trade t ON t.isin = i.isin AND t.is_closed = false
WHERE i.is_active = true
GROUP BY i.isin, i.description, i.currency, i.sub_asset, i.coupon_rate, i.maturity_date
HAVING COALESCE(
        SUM(CASE WHEN t.way = 'BUY'  THEN  t.nominal
                 WHEN t.way = 'SELL' THEN -t.nominal
                 ELSE 0 END), 0) > 0;
